Repository MicrosoftDocs/azure-reference-other, pull requests merged in 2018-10, with the labels that each got.

#44 Updated R packages with 3.4.4
  studio-module-reference/r-packages-supported-by-azure-machine-learning.md
Labels: Change sent to author, do-not-merge, machine-learning/svc

#47 typo: Double word "that"
  iot-c-reference/iot-c-ref-iothub-client-ll-h/iothubclient-ll-setoption.md
  iot-c-reference/iot-c-ref-iothub-device-client-ll-h/iothubdeviceclient-ll-setoption.md
  iot-c-reference/iot-c-ref-iothub-module-client-ll-h/iothubmoduleclient-ll-setoption.md
  studio-module-reference/import-from-azure-blob-storage.md
  studio-module-reference/one-class-support-vector-machine.md
Labels: Change sent to author, do-not-merge, machine-learning/svc

#48 typo: Double word "you"
  studio-module-reference/missing-values-scrubber-deprecated.md
Labels: Change sent to author, do-not-merge, machine-learning/svc

#49 typo: Double word "machine"
  studio-module-reference/index.md
  studio-module-reference/machine-learning-studio-algorithm-and-module-help.md
Labels: Change sent to author, do-not-merge, machine-learning/svc

#50 typo: Double word "on"
  studio-module-reference/execute-python-script.md
Labels: Change sent to author, do-not-merge, machine-learning/svc

#51 typo: Double word "is"
  iot-c-reference/iot-c-ref-iothub-client-core-common-h.md
  studio-module-reference/convert-to-csv.md
Labels: Change sent to author, do-not-merge, machine-learning/svc

#53 typo: Double word "value"
  iot-c-reference/iot-c-ref-httpapi-h.md
  iot-c-reference/iot-c-ref-httpapi-h/httpapi-cloneoption.md
  iot-c-reference/iot-c-ref-httpapi-h/httpapi-setoption.md
Labels: Change sent to author, do-not-merge

#46 typo: Double word "the"
  studio-module-reference/fisher-linear-discriminant-analysis.md
  studio-module-reference/unpack-zipped-datasets.md
  u-sql/extract-expression-u-sql.md
Labels: Change sent to author, data-lake-analytics/svc, do-not-merge

#52 typo: Double word "size"
  iot-c-reference/iot-c-ref-iothub-client-ll-h.md
  iot-c-reference/iot-c-ref-iothub-client-ll-h/iothubclient-ll-uploadtoblob.md
  iot-c-reference/iot-c-ref-iothub-device-client-ll-h.md
  iot-c-reference/iot-c-ref-iothub-device-client-ll-h/iothubdeviceclient-ll-uploadtoblob.md
Labels: Change sent to author, do-not-merge

#55 chore: Remove en-us from azure.microsoft.com links
  studio-module-reference/score-vowpal-wabbit-version-7-10-model.md
  studio-module-reference/score-vowpal-wabbit-version-8-model.md
  u-sql/u-sql-concepts.md
  u-sql/u-sql-credential-objects.md
  u-sql/u-sql-language-reference.md
Labels: Change sent to author, data-lake-analytics/svc, do-not-merge
