Repository MicrosoftDocs/azure-reference-other, pull requests merged in 2018-05, with the labels that each got.

#2 Typo fix, test
  studio-module-reference/add-columns.md
Labels: Change sent to author, machine-learning

#3 Typo fix, test
  studio-module-reference/add-rows.md
Labels: do-not-merge

#5 Confirm merge from repo_sync_working_branch to master to sync with https://github.com/MicrosoftDocs/azure-reference-other-pr (branch live)
  .openpublishing.publish.config.json
  stream-analytics-query-language/cast-azure-stream-analytics.md
  stream-analytics-query-language/complex-data-types-stream-analytics.md
  stream-analytics-query-language/data-types-azure-stream-analytics.md
  stream-analytics-query-language/getarrayelement-azure-stream-analytics.md
  stream-analytics-query-language/getarrayelements-azure-stream-analytics.md
  stream-analytics-query-language/getmetadatapropertyvalue.md
  stream-analytics-query-language/try-cast-azure-stream-analytics.md
Labels: Change sent to author, do-not-merge, stream-analytics
